import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

import { registerPingDuneServerTool } from './dune/pingDuneServer.js';
import { registerGetEvmBalancesTool } from './dune/getEvmBalances.js';
import { registerGetEvmActivityTool } from './dune/getEvmActivity.js';
import { registerGetEvmCollectiblesTool } from './dune/getEvmCollectibles.js';
import { registerGetEvmTransactionsTool } from './dune/getEvmTransactions.js';
import { registerGetEvmTokenInfoTool } from './dune/getEvmTokenInfo.js';
import { registerGetEvmTokenHoldersTool } from './dune/getEvmTokenHolders.js';
import { registerGetSvmBalancesTool } from './dune/getSvmBalances.js';
import { registerGetSvmTransactionsTool } from './dune/getSvmTransactions.js';
import { registerPingBlockscoutTool } from './blockscout/pingBlockscout.js';
import { registerBlockscoutSearchTool } from './blockscout/blockscoutSearch.js';
import { registerBlockscoutAddressInfoTool } from './blockscout/blockscoutAddressInfo.js';
import { registerBlockscoutAddressTransactionsTool } from './blockscout/blockscoutAddressTransactions.js';
import { registerBlockscoutAddressInternalTxsTool } from './blockscout/blockscoutAddressInternalTxs.js';
import { registerBlockscoutAddressLogsTool } from './blockscout/blockscoutAddressLogs.js';
import { registerBlockscoutAddressTokenBalancesTool } from './blockscout/blockscoutAddressTokenBalances.js';
import { registerBlockscoutTransactionDetailsTool } from './blockscout/blockscoutTransactionDetails.js';
import { registerBlockscoutTransactionLogsTool } from './blockscout/blockscoutTransactionLogs.js';
import { registerBlockscoutTransactionInternalTxsTool } from './blockscout/blockscoutTransactionInternalTxs.js';
import { registerBlockscoutTransactionRawTraceTool } from './blockscout/blockscoutTransactionRawTrace.js';
import { registerBlockscoutTransactionStateChangesTool } from './blockscout/blockscoutTransactionStateChanges.js';
import { registerBlockscoutBlockDetailsTool } from './blockscout/blockscoutBlockDetails.js';
import { registerBlockscoutBlockTransactionsTool } from './blockscout/blockscoutBlockTransactions.js';
import { registerBlockscoutLatestBlocksTool } from './blockscout/blockscoutLatestBlocks.js';
import { registerBlockscoutContractInfoTool } from './blockscout/blockscoutContractInfo.js';
import { registerBlockscoutContractMethodsTool } from './blockscout/blockscoutContractMethods.js';
import { registerBlockscoutReadContractTool } from './blockscout/blockscoutReadContract.js';
import { registerBlockscoutVerifiedContractsTool } from './blockscout/blockscoutVerifiedContracts.js';
import { registerBlockscoutTokenInfoTool } from './blockscout/blockscoutTokenInfo.js';
import { registerBlockscoutTokenTransfersTool } from './blockscout/blockscoutTokenTransfers.js';
import { registerBlockscoutTokenHoldersTool } from './blockscout/blockscoutTokenHolders.js';
import { registerBlockscoutNftInstancesTool } from './blockscout/blockscoutNftInstances.js';
import { registerBlockscoutNftMetadataTool } from './blockscout/blockscoutNftMetadata.js';
import { registerInvestigateSmartContractTool } from './compound/investigateSmartContract.js';
import { registerAnalyzeTransactionImpactTool } from './compound/analyzeTransactionImpact.js';
import { registerTokenDeepAnalysisTool } from './compound/tokenDeepAnalysis.js';
import { registerProfileWalletBehaviorTool } from './compound/profileWalletBehavior.js';

export function registerAllTools(server: McpServer) {
  registerPingDuneServerTool(server);
  registerGetEvmBalancesTool(server);
  registerGetEvmActivityTool(server);
  registerGetEvmCollectiblesTool(server);
  registerGetEvmTransactionsTool(server);
  registerGetEvmTokenInfoTool(server);
  registerGetEvmTokenHoldersTool(server);
  registerGetSvmBalancesTool(server);
  registerGetSvmTransactionsTool(server);
  registerPingBlockscoutTool(server);
  registerBlockscoutSearchTool(server);
  registerBlockscoutAddressInfoTool(server);
  registerBlockscoutAddressTransactionsTool(server);
  registerBlockscoutAddressInternalTxsTool(server);
  registerBlockscoutAddressLogsTool(server);
  registerBlockscoutAddressTokenBalancesTool(server);
  registerBlockscoutTransactionDetailsTool(server);
  registerBlockscoutTransactionLogsTool(server);
  registerBlockscoutTransactionInternalTxsTool(server);
  registerBlockscoutTransactionRawTraceTool(server);
  registerBlockscoutTransactionStateChangesTool(server);
  registerBlockscoutBlockDetailsTool(server);
  registerBlockscoutBlockTransactionsTool(server);
  registerBlockscoutLatestBlocksTool(server);
  registerBlockscoutContractInfoTool(server);
  registerBlockscoutContractMethodsTool(server);
  registerBlockscoutReadContractTool(server);
  registerBlockscoutVerifiedContractsTool(server);
  registerBlockscoutTokenInfoTool(server);
  registerBlockscoutTokenTransfersTool(server);
  registerBlockscoutTokenHoldersTool(server);
  registerBlockscoutNftInstancesTool(server);
  registerBlockscoutNftMetadataTool(server);
  registerInvestigateSmartContractTool(server);
  registerAnalyzeTransactionImpactTool(server);
  registerTokenDeepAnalysisTool(server);
  registerProfileWalletBehaviorTool(server);
}